package com.caloshape.backend.referral.domain;

public enum ReferralRejectReason {
    NONE,
    SELF_REFERRAL,
    INVITEE_ALREADY_CLAIMED,
    INVITEE_ALREADY_SUBSCRIBED,
    PREMIUM_ACTIVE,
    TRIAL_ACTIVE,
    PAYMENT_ISSUE,
    PAYMENT_RECOVERY_REQUIRED,
    HAS_PAID_HISTORY,
    REFERRAL_DISABLED,
    RISK_REJECTED,
    PURCHASE_NOT_VERIFIED,
    PURCHASE_PENDING,
    TEST_PURCHASE,
    REFUNDED_OR_REVOKED,
    CHARGEBACK,
    ABUSE_RISK,
    REWARD_GRANT_FAILED,
    VERIFICATION_WINDOW_EXPIRED,
    INVALID_PROMO_CODE
}
