package com.calai.backend.foodlog.model;

public enum FoodLogErrorCode {
    BAD_REQUEST,

    FILE_REQUIRED,
    FILE_TOO_LARGE,
    IMAGE_TOO_LARGE,
    UNSUPPORTED_IMAGE_FORMAT,
    UNSUPPORTED_CONTENT_TYPE,

    BARCODE_REQUIRED,
    BARCODE_INVALID,

    DATE_RANGE_REQUIRED,
    DATE_RANGE_INVALID,
    PAGE_SIZE_TOO_LARGE,

    FOOD_LOG_NOT_FOUND,
    FOOD_LOG_DELETED,
    FOOD_LOG_NOT_READY,
    FOOD_LOG_FAILED,
    FOOD_LOG_NOT_SAVABLE,
    FOOD_LOG_NOT_EDITABLE,
    FOOD_LOG_NOT_RETRYABLE,

    FIELD_KEY_INVALID,
    OVERRIDE_VALUE_INVALID,

    IMAGE_OBJECT_KEY_MISSING,
    PROVIDER_NOT_AVAILABLE,
    EMPTY_IMAGE,

    OBJECT_NOT_FOUND,
    INVALID_OBJECT_KEY,
    INTERNAL_ERROR;

    public String code() {
        return name();
    }
}